### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by Akineru** [kokoro-ele/Wordle4Hoshino#1]
服务器是Windows server，报错如下：
[2022-08-01 17:36:07,112 nonebot] ERROR: Failed to import "hoshino.modules.wordle.data_source", error: No module named 'sqlalchemy'
[2022-08-01 17:36:07,113 nonebot] ERROR: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\modules\wordle\__init__.py", line 11, in <module>
    from sqlalchemy import true
ModuleNotFoundError: No module named 'sqlalchemy'
[2022-08-01 17:36:07,122 nonebot] ERROR: Failed to import "hoshino.modules.wordle.utils", error: No module named 'sqlalchemy'
[2022-08-01 17:36:07,123 nonebot] ERROR: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\modules\wordle\__init__.py", line 11, in <module>
    from sqlalchemy import true
ModuleNotFoundError: No module named 'sqlalchemy'

请问该怎么解决呢

**Comment by kokoro-ele** [comment]
抱歉，我没注意到这行。直接将这行删掉就好了。

**Comment by kokoro-ele** [comment]
__init__文件中的from sqlalchemy import true

**Comment by Akineru** [comment]
>

**Comment by Akineru** [comment]
> __init__文件中的from sqlalchemy import true

感谢，已经解决了
